apiVersion: v1
kind: Secret
metadata:
  name: swarm-keydb-secrets
  namespace: swarm-keydb
type: Opaque
stringData:
  BEE_PASSWORD: replace-with-strong-password
  BEE_POSTAGE_BATCH_ID: replace-with-postage-batch-id