{{- if .Values.secret.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "swarm-keydb.secretName" . }}
  labels:
    {{- include "swarm-keydb.labels" . | nindent 4 }}
type: Opaque
stringData:
  BEE_POSTAGE_BATCH_ID: {{ .Values.secret.beePostageBatchId | quote }}
  SWARM_KEYDB_ENCRYPTION_KEY: {{ .Values.secret.encryptionKey | quote }}
  SWARM_KEYDB_ENCRYPTION_ETH_KEY: {{ .Values.secret.encryptionEthKey | quote }}
  SWARM_KEYDB_PRIVACY_KEY: {{ .Values.secret.privacyKey | quote }}
{{- end }}
